### ISSUE TITLE
Is partitioning staying in rig?

### ISSUE THREAD

**Issue by mossblaser** [mundya/rig#19]
Given the app-specific nature of partitioning, is this going to move back into nengo-spinnaker?

**Comment by mundya** [comment]
I think it should probably go, so removing `keyspace` from `Net` is fine.

**Comment by mossblaser** [comment]
I'll await it being removed from master before removing the field since it
breaks a load of tests of the partitioner.

**Comment by mundya** [comment]
Yah, I'll do that.
